# Generated by Django 3.2 on 2022-02-10 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(default=None, upload_to='')),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 2, 10, 14, 25, 10, 922398, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 2, 10, 14, 25, 10, 922398, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='magaz.articlecategory')),
            ],
            options={
                'verbose_name': 'категории',
                'verbose_name_plural': 'Публикации',
                'ordering': ['title'],
            },
        ),
    ]
